In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [10]:
from imblearn.over_sampling import ADASYN, SMOTE

In [168]:
phtrain = pd.read_csv('processed_health_train')

In [169]:
phtrain.head()

x1     x2  x3     x4     x5     x6     x7   x8   x9   x10  ...    x16  \
0  1406  145.0   1  0.005  0.000  0.002  0.000  0.0  0.0  46.0  ...  104.0   
1   258  127.0   0  0.012  0.000  0.008  0.004  0.0  0.0  13.0  ...   53.0   
2   479  145.0   1  0.000  0.000  0.000  0.002  0.0  0.0  57.0  ...  111.0   
3   906  146.0   1  0.004  0.000  0.005  0.003  0.0  0.0  29.0  ...  107.0   
4  1921  140.0   1  0.002  0.003  0.006  0.006  0.0  0.0  62.0  ...   75.0   

     x17   x18  x19    x20    x21    x22   x23  x24  target  
0  171.0   4.0  0.0  155.0  153.0  154.0   4.0  1.0       1  
1  191.0  12.0  1.0  133.0  126.0  131.0  41.0  0.0       1  
2  157.0   1.0  1.0  150.0  146.0  149.0   6.0  1.0       1  
3  169.0   2.0  2.0  150.0  147.0  149.0   7.0  0.0       1  
4  228.0   9.0  0.0  142.0  118.0  142.0  20.0  0.0       1  

[5 rows x 25 columns]

In [170]:
X = phtrain.drop('target', axis=1)
y = phtrain['target']

In [34]:
adasyn = ADASYN()
X_resampled, y_resampled = smote.fit_resample(X, y)

In [14]:
smote = SMOTE()

In [15]:
X_resampled, y_resampled = smote.fit_resample(X, y)

In [35]:
df_resampled = pd.concat([pd.DataFrame(X_resampled, columns=X.columns), pd.DataFrame(y_resampled, columns=['target'])], axis=1)

In [36]:
df_resampled.head()

x1     x2  x3     x4     x5     x6     x7   x8   x9   x10  ...    x16  \
0  1406  145.0   1  0.005  0.000  0.002  0.000  0.0  0.0  46.0  ...  104.0   
1   258  127.0   0  0.012  0.000  0.008  0.004  0.0  0.0  13.0  ...   53.0   
2   479  145.0   1  0.000  0.000  0.000  0.002  0.0  0.0  57.0  ...  111.0   
3   906  146.0   1  0.004  0.000  0.005  0.003  0.0  0.0  29.0  ...  107.0   
4  1921  140.0   1  0.002  0.003  0.006  0.006  0.0  0.0  62.0  ...   75.0   

     x17   x18  x19    x20    x21    x22   x23  x24  target  
0  171.0   4.0  0.0  155.0  153.0  154.0   4.0  1.0       1  
1  191.0  12.0  1.0  133.0  126.0  131.0  41.0  0.0       1  
2  157.0   1.0  1.0  150.0  146.0  149.0   6.0  1.0       1  
3  169.0   2.0  2.0  150.0  147.0  149.0   7.0  0.0       1  
4  228.0   9.0  0.0  142.0  118.0  142.0  20.0  0.0       1  

[5 rows x 25 columns]

In [18]:
print(df_resampled['target'].value_counts())

1    1155
2    1155
3    1155
Name: target, dtype: int64


In [151]:
df_resampled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3465 entries, 0 to 3464
Data columns (total 25 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   x1      3465 non-null   int64  
 1   x2      3465 non-null   float64
 2   x3      3465 non-null   int64  
 3   x4      3465 non-null   float64
 4   x5      3465 non-null   float64
 5   x6      3465 non-null   float64
 6   x7      3465 non-null   float64
 7   x8      3465 non-null   float64
 8   x9      3465 non-null   float64
 9   x10     3465 non-null   float64
 10  x11     3465 non-null   float64
 11  x12     3465 non-null   float64
 12  x13     3465 non-null   float64
 13  x14     3465 non-null   int64  
 14  x15     3465 non-null   float64
 15  x16     3465 non-null   float64
 16  x17     3465 non-null   float64
 17  x18     3465 non-null   float64
 18  x19     3465 non-null   float64
 19  x20     3465 non-null   float64
 20  x21     3465 non-null   float64
 21  x22     3465 non-null   float64
 22  

In [171]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=101)

In [154]:
#Oversampling the training data
adasyn = ADASYN()
X_resampled, y_resampled = adasyn.fit_resample(X_train, y_train)

In [160]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=101)

In [162]:
dt_clf = DecisionTreeClassifier()

dt_clf.fit(X_train1, y_train1)
y_pred1 = dt_clf.predict(X_test1)

In [163]:
accuracy = accuracy_score(y_test1, y_pred1)
print("Accuracy:", accuracy)

Accuracy: 0.9678456591639871


In [164]:
y_pred = dt_clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8979591836734694


# Decision Tree Algorithm

In [86]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [137]:
X = phtrain.drop('target', axis=1)
y = phtrain['target']

In [138]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [89]:
dt_clf = DecisionTreeClassifier()

dt_clf.fit(X_train, y_train)
y_pred = dt_clf.predict(X_test)

In [165]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8979591836734694


In [166]:
print(confusion_matrix(y_test, y_pred))

[[109   4   2]
 [  3  15   6]
 [  0   0   8]]


In [167]:
print(confusion_matrix(y_test1, y_pred1))

[[204   7   0]
 [  9 191   2]
 [  2   0 207]]


# Decision Tree after resampling

In [91]:
X_resampled = df_resampled.drop('target', axis=1)
y_resampled = df_resampled['target']

In [92]:
Xre_train, Xre_test, yre_train, yre_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=101)

In [147]:
dtre_clf = DecisionTreeClassifier()

dtre_clf.fit(X_resampled, y_resampled)
yre_pred = dtre_clf.predict(X_test)

In [148]:
accuracy_re = accuracy_score(y_test, yre_pred)
print("Accuracy:", accuracy_re)

Accuracy: 0.8945578231292517


# Random Forest

In [95]:
from sklearn.ensemble import RandomForestClassifier

In [96]:
rf_clf = RandomForestClassifier()
rf_clf.fit(X_train, y_train)
y_pred = rf_clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9319727891156463


In [97]:
rfre_clf = RandomForestClassifier()
rfre_clf.fit(Xre_train, yre_train)
yre_pred = rfre_clf.predict(Xre_test)

accuracy_re = accuracy_score(yre_test, yre_pred)
print("Accuracy:", accuracy_re)

Accuracy: 0.976911976911977


In [124]:
import xgboost as xgb

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)

In [172]:
#xgb_model = xgb.XGBClassifier(learning_rate=0.5,n_estimators=800,max_depth=40)

xgb_model = xgb.XGBClassifier(objective="multi:softprob", random_state=42, max_depth=40, learning_rate=0.5)

In [173]:
xgb_model.fit(X_train, y_train)

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2], got [1 2 3]

In [127]:
y_pred = xgb_model.predict(X_test)

In [128]:
y_test = le.fit_transform(y_test)

In [129]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9421768707482994


In [130]:
print(confusion_matrix(y_test, y_pred))

[[217   4   2]
 [  9  38   2]
 [  0   0  22]]


# KNN Classifier

In [140]:
from sklearn.neighbors import KNeighborsClassifier

clf_nn = KNeighborsClassifier(n_neighbors=3)

In [144]:
clf_nn.fit(X_resampled,y_resampled)

KNeighborsClassifier(n_neighbors=3)

In [145]:
y_pred = clf_nn.predict(X_test)

In [146]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8639455782312925


# Logistic Regression

In [139]:
adasyn = ADASYN()
X_resampled, y_resampled = adasyn.fit_resample(X_train, y_train)